name: nabilov/RxJava
author:
  name: Nabil LARIBI
  email: nabil.laribi@gmail.com
  url: 'https://twitter.com/nabilovu'
copyright: 2015 Nabil LARIBI
description: RxJava – Reactive Extensions for the JVM – a library for composing asynchronous and event-based programs using observable sequences for the Java VM.
